name: Build Conda Packages

on:
  push:
    branches: 'master'
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  Build-Conda:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        # MacOS-14 suddenly does not build anymore and shows dumb errors such as:
        # /Users/runner/work/indexed_bzip2/indexed_bzip2/MacOSX10.9.sdk/usr/include/sys/_types.h:94:9:
        #   error: unknown type name '__int64_t'
        # MacOS 12 and 13 ALSO suddenly do not build anymore because of:
        # > ld: unsupported tapi file type '!tapi-tbd' in YAML file
        # https://stackoverflow.com/questions/74318052/
        #   cant-compile-fortran-on-macos-monterey-ld-unsupported-tapi-file-type-tapi-t
        # Windows builds fine, but suddenly returns with non-zero exit code in 7dafe65 even though
        # nothing changed. Maybe an issue with a new conda version. 3ca62ea did build just fine.
        # 2024-05: Windows suddenly fails with a non-descriptive error even though I have changed NOTHING (I reran
        #          a previously successful CI run). I don't have the patience to fix this unused shit.
        #          For some reason the much more complex rapidgzip conda still works, though ...
        #os: [macos-latest, ubuntu-latest, windows-latest]

    env:
      MACOSX_DEPLOYMENT_TARGET: "13.0"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true

    - name: Fix macOS CommandLineTools Bug
      if: matrix.os == 'macos-latest'
      shell: bash
      run: |
        # Fixes:
        #   ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libSystem.tbd' for architecture x86_64
        #   clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
        #   error: command '/usr/local/miniconda/conda-bld/indexed_bzip2_1630845496646/_build_env/bin/x86_64-apple-darwin13.4.0-clang++' failed with exit code 1
        #   -> It seems like the conda build script uses the clang compiler installed into the conda environment but then tries to call the ld command from the system and their versions do clash!
        #
        # https://docs.ligo.org/lscsoft/conda/compiling/#installing-the-macos-sdk
        # https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html#macos-sdk
        # https://github.com/ContinuumIO/anaconda-issues/issues/9096#issuecomment-378655747
        # https://github.com/conda/conda-build/issues/2719#issuecomment-369484512
        #
        wget https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.9.sdk.tar.xz
        tar -xf MacOSX10.9.sdk.tar.xz
        cat <<EOF >> conda/conda_build_config.yaml
        CONDA_BUILD_SYSROOT:
          - $PWD/MacOSX10.9.sdk
        EOF
        mkdir -p "$HOME/Library/Application Support/pip"
        cat <<EOF >> "$HOME/Library/Application Support/pip/pip.conf"
        [global]
        break-system-packages = true
        EOF

    - name: Set Up Conda
      # Bash shells do not use ~/.profile or ~/.bashrc so these shells need to be explicitly declared as shell:
      # bash -l {0} on steps that need to be properly activated
      shell: bash -l {0}
      working-directory: python/indexed_bzip2/conda
      run: |
        conda install conda conda-build anaconda-client conda-verify packaging
        conda config --add channels conda-forge
        conda config --set report_errors false
        conda config --set anaconda_upload no
        python3 -m pip install build
        python3 -m build -o . --sdist ..
        mv indexed_bzip2-*.tar* src.tar

    - name: Build Conda Packages
      if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
      shell: bash -l {0}
      working-directory: python/indexed_bzip2/conda
      run: |
        conda build .

    - name: Publish Conda Packages
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      shell: bash -l {0}
      working-directory: python/indexed_bzip2/conda
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        conda config --set anaconda_upload yes
        conda build --token "$ANACONDA_TOKEN" .
